### PR TITLE
Scripts for downloading data and NBDT arena app.py

### PR DESCRIPTION
**Pull request by S-panda1**

### CODE REVIEW

**Comment by titipata** [comment]
- Add a description to this PR (in the comment)
- Change notebook names to something more meaningful 
- In the code, specify input types such as `def get_comp(prompt: str):`

**Comment by S-panda1** [comment]
- Added `data_download`  folder with all the scripts to download journal data, along with how to use the individual scripts.
- Added `arena` folder, with a streamlit app to rate the models and documentation on how to run the streamlit app locally and how to create a custom vector database.

**Comment by titipata** [comment]
LGTM

**Review by titipata — APPROVED** [review]
LGTM

**Pull request merged**
